### ISSUE TITLE
[tslint] Properties should be separated by semicolons (semicolon)

### ISSUE THREAD

**Issue by aasril** [angular-in-action/datacenter#1]
Writing the code on VS Code, ts lint gives that error when Interface's properties separated by commas instead of by semicolons. Also, in [typescript documentation](https://www.typescriptlang.org/docs/handbook/interfaces.html)  they use semicolons instead of commas.

**Comment by gnomeontherun** [comment]
Yes, this is true. I think it was not so strict back when I wrote the code originally. It shouldn't stop it from compiling, or if it does its an easy fix by running this from the main directory to autofix it.

`npx tslint -p . -c tslint.json --fix`
