### ISSUE TITLE
Error in Chapter 6

### ISSUE THREAD

**Issue by wybeturing** [angular-in-action/datacenter#4]
In chapter 6, the instructions are to open the src/app/dashboard/dashboard.component.html file and update it to have the following template:
`<app-navbar (onRefresh)="refresh()"></app-navbar>
<ng-template #alertBox></ng-template>
<app-dashboard></app-dashboard>`
That seems to be an error. The change should be made in the app.component.html file instead.

**Comment by gnomeontherun** [comment]
Hi @WybeTuring you can always step through the code by looking at the git commit history to be sure things are right. I can't change the printed book, but the live version has been updated with some typos I believe.

**Comment by wybeturing** [comment]
Thanks @gnomeontherun! And thanks for the book. It has made a tremendous contribution to my growth as an Angular developer.

**Comment by gnomeontherun** [comment]
Happy to help and glad you have enjoyed the book!
